import { ComboEntry } from './types';

export const caitlynCombos: ComboEntry[] = [

  // ═══════════════════════════════════════════════════════════════
  // 0 BAR COMBOS
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'bnb-universal',
    name: 'Universal BnB',
    notation: '5L > 5M > 2H > 9 > jL > jM > jH > jS2',
    difficulty: 'beginner',
    position: 'anywhere',
    damage: null,
    meter: 0,
    starter: '5L',
    hasAssist: false,
    notes: 'Simplest combo. Knockdown ender. Learn this first.',
  },
  {
    id: 'bnb-intermediate',
    name: 'Intermediate BnB',
    notation: '5M > 5H > 2H > jH > jS1 > j[S1] > 66 > 6S2',
    difficulty: 'beginner',
    position: 'anywhere',
    damage: 331,
    meter: 0,
    starter: '5M',
    hasAssist: false,
    notes: 'Introduces partially charged S1 timing.',
  },
  {
    id: 'midscreen-extended',
    name: 'Midscreen Extended',
    notation: '5L > 5M > 5H > 2H > 2S1 > 2[S1] > 66 > 5M > 5H > 2H > jM > jH > jS1 > jS2',
    difficulty: 'intermediate',
    position: 'midscreen',
    damage: 316,
    damageMax: 591,
    meter: 0,
    starter: '5L',
    hasAssist: false,
    notes: 'Uses 2S1 wall bounce for midscreen extension. Damage range reflects different enders.',
  },
  {
    id: 'corner-sideswitch',
    name: 'Corner Sideswitch',
    notation: '5L > 5M > 5H > 4H > dl.2S1 > [S1] > 5M > 5H > 2H > 9 > jM > jH > jS1 > jS2',
    difficulty: 'intermediate',
    position: 'corner',
    damage: 328,
    meter: 0,
    starter: '5L',
    hasAssist: false,
    notes: 'Escapes corner with 4H side-switch. Delay the 2S1 carefully.',
  },
  {
    id: 'corner-limit-strike',
    name: 'Corner Limit Strike',
    notation: '5L > 5M > 5H > 2H > 9 > jH > j2H > 2S2 > 5[H] > 4H > 9 > jS1 > jS2 > 6S2 > jS1 > jS2 > 6S2',
    difficulty: 'advanced',
    position: 'corner',
    damage: 345,
    meter: 0,
    meterGain: 98,
    starter: '5L',
    hasAssist: false,
    notes: 'Builds nearly a full bar (98 meter). Keeps corner.',
  },

  // ═══════════════════════════════════════════════════════════════
  // 1 BAR COMBOS (1 super used)
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'anti-air-full',
    name: 'Anti-Air Full Extension',
    notation: '2M > M > H > 9 > jM > jH > jS1 > j{S1} > 66 > M > H > 2H > 9 > H > j2H > j2S2 > Super 1',
    difficulty: 'intermediate',
    position: 'anywhere',
    damage: 481,
    meter: 1,
    starter: '2M',
    hasAssist: false,
    notes: 'Full damage anti-air confirm. Aim Super 1 at head for extra damage.',
  },
  {
    id: 'trap-restand',
    name: 'Trap Restand BnB',
    notation: '5M > 5H > 6S1~L/M/H > 6S2 > j2S2 > 66 > 5M > 5H > S1 > S1 > Super 1',
    difficulty: 'intermediate',
    position: 'anywhere',
    damage: 437,
    damageMax: 613,
    meter: 1,
    starter: '5M',
    hasAssist: false,
    notes: 'Core restand route. 6S1 button choice adjusts trap angle.',
  },
  {
    id: 'corner-trap-restand',
    name: 'Corner Trap Restand',
    notation: 'M > 2M > H > 2H > 8S2 > M > H > 2H > 9 > jM > jH > jS1 > jS2 > 6S2 > j2S2 > Super 1',
    difficulty: 'intermediate',
    position: 'corner',
    damage: 518,
    meter: 1,
    meterGain: 66,
    starter: '5M',
    hasAssist: false,
    notes: 'Aim Super 1 at head. Builds 66 meter back.',
  },
  {
    id: 'advanced-midscreen',
    name: 'Advanced Midscreen',
    notation: 'M > 2M > H > 2H > 9 > jM > jH > j2S1 > j4S2 > j2H > 2S2 > {H} > 4H > 9S1 > jS2 > 6S2 > j2S2 > Super 1',
    difficulty: 'advanced',
    position: 'midscreen',
    damage: null,
    meter: 1,
    starter: '5M',
    hasAssist: false,
    notes: 'Aim Super 1 at head.',
  },
  {
    id: 'super2-anywhere',
    name: 'Super 2 (Hexshield) Route',
    notation: '2M > M > H > 9 > jM > jH > j4S2 > jH > M > H > 9 > jM > j2H > j2S2 > 44 > 6H > {S1} > 6{S1} > {H} > 6S2 > Super 2',
    difficulty: 'advanced',
    position: 'anywhere',
    damage: null,
    meter: 1,
    starter: '2M',
    hasAssist: false,
    notes: 'Ends in Super 2 (Hexshield). Empowers follow-up rifle shots.',
  },

  // ═══════════════════════════════════════════════════════════════
  // TAG COMBOS
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'tag-darius',
    name: 'Caitlyn + Darius',
    notation: '5M > 5H > 6S1~L/M/H > 6S2 > T > 66 > 5M > 5H > 2H > jM > jH > jS1 > j[S1]',
    difficulty: 'intermediate',
    position: 'anywhere',
    damage: 374,
    meter: 0,
    starter: '5M',
    hasAssist: true,
    partner: 'Darius',
    notes: '0-bar tag combo.',
  },
  {
    id: 'tag-warwick-corner',
    name: 'Caitlyn + Warwick Corner',
    notation: '5M > 5H > S1 > 6S1 > Super 2 > [T] > 3H > 6S1 > 5M > 5H > 2H > jM > jH > jS1 > 6S2 > S2~S2~S2 > T > Super 2 > T > [S1] > [S1] > Super 1',
    difficulty: 'advanced',
    position: 'corner',
    damage: 755,
    meter: 3,
    starter: '5M',
    hasAssist: true,
    partner: 'Warwick',
    notes: '75% HP. Uses 3 supers across both characters. Aim slightly up on charged S1.',
  },
];
