import { ComboEntry } from './types';

export const ekkoCombos: ComboEntry[] = [

  // 0 BAR COMBOS
  {
    id: 'ekko-0bar-1',
    name: '0-Bar BnB',
    notation: 'M > 2H > 9M > H > S2 > 2S2 > 9M > H > S2',
    position: 'anywhere',
    damage: 276,
    meter: 0,
    starter: 'M',
    hasAssist: false,
  },
  {
    id: 'ekko-0bar-2',
    name: '0-Bar BnB',
    notation: 'M > H > 2H > 9M > H > S2 > 2S2 > 9M > H > S2',
    position: 'anywhere',
    damage: 351,
    meter: 0,
    starter: 'M',
    hasAssist: false,
  },
  {
    id: 'ekko-0bar-3',
    name: '0-Bar BnB',
    notation: 'L > M > 2H > 9M > H > S2 > 2S2 > 9M > H > S2',
    position: 'anywhere',
    damage: 276,
    meter: 0,
    starter: 'L',
    hasAssist: false,
  },
  {
    id: 'ekko-0bar-4',
    name: '0-Bar BnB',
    notation: 'L > M > H > 2H > 9M > H > S2 > 2S2 > 9M > H > S2',
    position: 'anywhere',
    damage: 291,
    meter: 0,
    starter: 'L',
    hasAssist: false,
  },
  {
    id: 'ekko-0bar-5',
    name: '0-Bar BnB',
    notation: 'L > M > H > 2H > 9M > H > D > H > S2 > M > H > 2H > 9M > H > S2',
    position: 'anywhere',
    damage: null,
    meter: 0,
    starter: 'L',
    hasAssist: false,
  },
  {
    id: 'ekko-0bar-6',
    name: '0-Bar BnB',
    notation: 'L > M > H > 2H > 9M > H > D > H > S2 > 2S2 > 9M > H > D > H > S2',
    position: 'anywhere',
    damage: null,
    meter: 0,
    starter: 'L',
    hasAssist: false,
  },
  {
    id: 'ekko-0bar-7',
    name: '0-Bar BnB',
    notation: '2H > 9M > H > D > H > S2 > 2S2 > JCM > H > D > H > S2',
    position: 'anywhere',
    damage: null,
    meter: 0,
    starter: '2H',
    hasAssist: false,
  },
  {
    id: 'ekko-0bar-8',
    name: '0-Bar BnB',
    notation: 'M > H > 2H > 9M > H > S2 > 2S2 > JCM > H > S2',
    position: 'anywhere',
    damage: null,
    meter: 0,
    starter: 'M',
    hasAssist: false,
  },
  {
    id: 'ekko-0bar-9',
    name: '0-Bar BnB',
    notation: '2L > 2M > M > 2H > 9S2 > 2S2 > 2S2 > M > 2H > 9HH > S1 > S2 > 2H > 9H > S2',
    position: 'anywhere',
    damage: null,
    meter: 0,
    starter: '2L',
    hasAssist: false,
  },
  {
    id: 'ekko-0bar-10',
    name: '0-Bar BnB',
    notation: '2L > 2M > M > 2H > 9S2 > 2 > 4S2 > S1 > 2S2 > 2H > 9HH > S1 > S2 > H > 2T',
    position: 'anywhere',
    damage: null,
    meter: 0,
    starter: '2L',
    hasAssist: false,
  },
  {
    id: 'ekko-0bar-11',
    name: '0-Bar BnB',
    notation: 'M > H > S2 > 2S2 > 9M > H > S2 > H > 2T',
    position: 'anywhere',
    damage: null,
    meter: 0,
    starter: 'M',
    hasAssist: false,
  },

  // 1 BAR COMBOS
  {
    id: 'ekko-1bar-1',
    name: '1-Bar Route',
    notation: 'M > H > S2 > S1+L > 2H > 9S1 > M > 2H > 9M > H > S2',
    position: 'anywhere',
    damage: 475,
    meter: 1,
    starter: 'M',
    hasAssist: false,
  },
  {
    id: 'ekko-1bar-2',
    name: '1-Bar Route',
    notation: 'L > M > H > S2 > S2 > S1+L > 2H > S1 > 2S2 > 2HH > 9HH > S1 > S2 > H > 2T',
    position: 'anywhere',
    damage: null,
    meter: 1,
    starter: 'L',
    hasAssist: false,
  },
  {
    id: 'ekko-1bar-3',
    name: '1-Bar Route',
    notation: 'L > M > H > S2 > S2 > S1+L > 2H > 2S1 > 9 > HH > 2S2 > 2H > JCH > S',
    position: 'anywhere',
    damage: null,
    meter: 1,
    starter: 'L',
    hasAssist: false,
  },
  {
    id: 'ekko-1bar-4',
    name: '1-Bar Route',
    notation: '2L > M > S2 > S2 > S1+L > 2H > 2HH > 9M > H > S2',
    position: 'anywhere',
    damage: null,
    meter: 1,
    starter: '2L',
    hasAssist: false,
  },
  {
    id: 'ekko-1bar-5',
    name: '1-Bar Route',
    notation: 'M > H > S2 > S2 > S1+L > 2H > (4)S1 > 2S2 > 2H > 9HH > S1 > S2 > S1+L',
    position: 'anywhere',
    damage: null,
    meter: 1,
    starter: 'M',
    hasAssist: false,
  },

  // CORNER COMBOS
  {
    id: 'ekko-corner-1',
    name: 'Corner Route',
    notation: 'L > M > H > S2 > S2 > L > M > H > S2 > 2S2 > JCS2S2 > 2S2 > 2H > 9H > S2',
    position: 'corner',
    damage: null,
    meter: 0,
    starter: 'L',
    hasAssist: false,
  },
  {
    id: 'ekko-corner-2',
    name: 'Corner Route',
    notation: 'L > M > H > S2 > S2 > L > H > S2 > 2S2 > 9S2S2 > L > M > H > 6S1 > 2S2 > 6S1 > S1+S2',
    position: 'corner',
    damage: null,
    meter: 3,
    starter: 'L',
    hasAssist: false,
  },
  {
    id: 'ekko-corner-3',
    name: 'Corner Route',
    notation: 'L > M > H > S2 > S2 > L > H > S2 > 2S2 > JCS2S2 > L > M > H > 6S1 > 2S2 > 6S1 > S1+L',
    position: 'corner',
    damage: null,
    meter: 1,
    starter: 'L',
    hasAssist: false,
  },

  // TAG COMBOS
  {
    id: 'ekko-tag-1',
    name: 'Ekko + Jinx',
    notation: 'L > M > H > S2 > S1+L > S1+L',
    position: 'anywhere',
    damage: 403,
    meter: 2,
    starter: 'L',
    hasAssist: true,
    partner: 'Jinx',
    fuse: 'Double Down',
  },
  {
    id: 'ekko-tag-2',
    name: 'Ekko + Jinx',
    notation: 'M > H > S2 > S1+L > S1+L',
    position: 'anywhere',
    damage: 445,
    meter: 2,
    starter: 'M',
    hasAssist: true,
    partner: 'Jinx',
    fuse: 'Double Down',
  },
  {
    id: 'ekko-tag-3',
    name: 'Ekko + Jinx',
    notation: 'M > H > S2 > S2 > S1+L > 2H > 9S1 > M > 2T > M > H > S1 > S2 > S1+L',
    position: 'anywhere',
    damage: 630,
    meter: 2,
    starter: 'M',
    hasAssist: true,
    partner: 'Jinx',
  },
  {
    id: 'ekko-tag-4',
    name: 'Ekko + Jinx',
    notation: 'M > H > S2 > S2 > S1+L > 2H > 9S1 > M > 2T > M > H > 2H > 2S2 > S2 > 9M > S2+M',
    position: 'anywhere',
    damage: 635,
    meter: 2,
    starter: 'M',
    hasAssist: true,
    partner: 'Jinx',
  },
  {
    id: 'ekko-tag-5',
    name: 'Ekko + Jinx',
    notation: '3M > 4T > M > H > S2 > 2S2 > 9M > H > S2 > 2M > H > 6S1',
    position: 'anywhere',
    damage: 424,
    meter: 0,
    starter: '3M',
    hasAssist: true,
    partner: 'Jinx',
  },
  {
    id: 'ekko-tag-6',
    name: 'Ekko + Jinx',
    notation: '3M > 4T > M > H > S2 > 2S2 > 9S2S2 > L > M > H > 6S1 > 2S2 > H > 2T > H > 2H > HH > 2S2 > S1+L',
    position: 'corner',
    damage: 624,
    meter: 1,
    starter: '3M',
    hasAssist: true,
    partner: 'Jinx',
  },

];
